### Import thư viện và nhập dữ liệu

In [46]:
import pandas as pd
from collections import defaultdict
import csv

In [47]:
URL = ["https://ckns.mof.gov.vn/SitePages/nsdp-qt-Chi.aspx", "https://cknsanalysis.mof.gov.vn/custom/single/?appid=d18e8b76-f3c3-4193-8aeb-0160a9385bca&sheet=bcb6df54-3983-4ec0-be9c-5be8ffc72c2b&select=clearall&qlikTicket="]

In [48]:
df = pd.read_excel('data-crawl-from-web.xlsx')
df

,Unnamed: 0,Đơn vị tính: Triệu đồng,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Năm báo cáo,2018,2019,2020,2021,2022,2023
1,NaN,Các chỉ tiêu,Chi giáo dục - đào tạo và dạy nghề,Chi giáo dục - đào tạo và dạy nghề,Chi giáo dục - đào tạo và dạy nghề,Chi giáo dục - đào tạo và dạy nghề,Chi giáo dục - đào tạo và dạy nghề,Chi giáo dục - đào tạo và dạy nghề
2,Địa phương,So sánh,Dự toán NS cấp Tỉnh,Dự toán NS cấp Tỉnh,Dự toán NS cấp Tỉnh,Dự toán NS cấp Tỉnh,Dự toán NS cấp Tỉnh,Dự toán NS cấp Tỉnh
3,An Giang,NaN,698.327,770.919,706.612,715.631,-,-
4,Bà Rịa - Vũng Tàu,NaN,NaN,NaN,1.685.634,1.239.637,1.404.207,-
...,...,...,...,...,...,...,...,...
58,Trà Vinh,NaN,NaN,770.248,671.181,623.709,572.624.000.000,-
59,Tuyên Quang,NaN,235.076,249.006,497.946,551.997,867.196,-
60,Vĩnh Long,NaN,446.658,639.362,497.794,489.990,530.110,-
61,Vĩnh Phúc,NaN,NaN,885.210,1.007.542,828.292,-,-
62,Yên Bái,NaN,748.161,594.146,538.622,526.685,526.685,-

In [49]:
df.shape #Thiếu Huế, Bình Phước, Bình Thuận

(63, 8)

### Xóa hai hàng đầu

In [50]:
df = df.drop([0, 1, 2])
df = df.reset_index(drop=True)

df.head()

,Unnamed: 0,Đơn vị tính: Triệu đồng,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,An Giang,NaN,698.327,770.919,706.612,715.631,-,-
1,Bà Rịa - Vũng Tàu,NaN,NaN,NaN,1.685.634,1.239.637,1.404.207,-
2,Bắc Giang,NaN,880.775,777.001,893.298,855.066,840.194,-
3,Bắc Kạn,NaN,NaN,275.112,0,187.094,463.753,-
4,Bạc Liêu,NaN,472.639,880.247,277.847,367.387,602.971,-

### Xóa cột thứ 2

In [51]:
df = df.drop(df.columns[1], axis=1)

df.head()

,Unnamed: 0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,An Giang,698.327,770.919,706.612,715.631,-,-
1,Bà Rịa - Vũng Tàu,NaN,NaN,1.685.634,1.239.637,1.404.207,-
2,Bắc Giang,880.775,777.001,893.298,855.066,840.194,-
3,Bắc Kạn,NaN,275.112,0,187.094,463.753,-
4,Bạc Liêu,472.639,880.247,277.847,367.387,602.971,-

### Đổi tên cột đầu thành địa phương, cột thứ 2 thành 2018, cột thứ 3 thành 2019, cột thứ 4 thành 2020, cột thứ 5 thành 2021, cột thứ 6 thành 2022, cột thứ 7 thành 2023

In [52]:
df.columns = ['Địa phương', '2018', '2019', '2020', '2021', '2022', '2023']

df.head()

          Địa phương     2018     2019       2020       2021       2022 2023
0           An Giang  698.327  770.919    706.612    715.631          -    -
1  Bà Rịa - Vũng Tàu      NaN      NaN  1.685.634  1.239.637  1.404.207    -
2          Bắc Giang  880.775  777.001    893.298    855.066    840.194    -
3            Bắc Kạn      NaN  275.112          0    187.094    463.753    -
4           Bạc Liêu  472.639  880.247    277.847    367.387    602.971    -

### Lưu dưới dạng file csv

In [53]:
data = defaultdict(lambda: defaultdict(lambda: 0))

for i in range(0, df.shape[0]):
    for year in range(2018, 2023):
        data[df.at[i, "Địa phương"]][year] = df.at[i, str(year)]

# Mở file CSV để ghi
with open('education.csv', 'w', newline='', encoding='utf-8') as csvfile:
    fieldnames = ['Địa phương', 'Năm', 'Chi tiêu cho giáo dục']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    # Viết header
    writer.writeheader()

    # Viết dữ liệu từ data vào file CSV
    for province, years in data.items():
        for year, value in years.items():
            writer.writerow({'Địa phương': province, 'Năm': year, 'Chi tiêu cho giáo dục': value})